### ISSUE TITLE
Human Readable Time Flag

### ISSUE THREAD

**Issue by CaptainPickles89** [forquare/zht#6]
ZHT is great, but what would make it even better is if there were an option/flag to convert the epoch time to human readable:

**Current behaviour:**
`❯ zht search rbenv
: 1664879909:0;rbenv rehash`

**Suggested behaviour:**
`❯ zht -t search rbenv
: Tuesday, 4 October 2022 10:38:29:0;rbenv rehash`

**Comment by forquare** [comment]
This is now available as part of zht 0.1.1 😊
