### ISSUE TITLE
Past Search Ignore Flag

### ISSUE THREAD

**Issue by CaptainPickles89** [forquare/zht#7]
Having zht to search through the history is useful but I think it would help if there was a flag to ignore past zht searches for cases where the same/similar searches are run often. if there were a flag that ignored/dropped any records starting with "zht" that may help to find the wanted command quicker.

**Current Example:**
`❯ zht search rbenv
: 1664893016:0;rbenv global
: 1664893152:0;rbenv versions
: 1664895632:0;zht search rbenv
: 1664896781:0;zht search rbenv
: 1664896909:0;rbenv versions`

**Suggested Example:**
`❯ zht -p search rbenv
: 1664893016:0;rbenv global
: 1664893152:0;rbenv versions
: 1664896909:0;rbenv versions`

**Comment by forquare** [comment]
Ha! Yes!

I saw this earlier and couldn’t understand what you were asking for, but now I do!

Yes, I think this is easy enough to do!

**Comment by forquare** [comment]
This should be Resolved by #12 (version [0.2.0](https://github.com/forquare/zht/releases/tag/0.2.0))

By default it will ignore any commands that *start*:

* `zht`
* `./zht`

If you want to go back to the old functionality then you can pass `zht search -S <mysearch>`
